name: Production Deploy

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: nppweb/infra/.github/workflows/deploy.yml@master
    with:
      repo_name: scrape-helper
      branch: ${{ github.ref_name }}
      target_sha: ${{ github.sha }}
      auto_rollback: true
    secrets: inherit
